# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 681d09d36cd73896ef99b64bb7e5f09a8444a404387695a3e628546208ee8131f274d1b7af9eefc33c60b13bdd059c14675c05d981eb23aff5baa5551605ba89

test:
  secret_key_base: d47421b2f2c16bcad73a05034c8d9e4b11e22e231bc62ad31884a49d865c0ffd4886ed76cc6fbb57bb34784e642ec990bf3590ba5b50e3ca0f3427cb08cbef06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
